import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import ts from 'typescript';
function load(file, imports = {}) { const source=readFileSync(new URL(file,import.meta.url),'utf8');const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};new Function('exports','require',code)(exports,(name)=>imports[name]);return exports; }
const domain=load('./member-overall.ts');
const client=load('./member-overall-client.ts',{'./member-overall':domain});
const id='71000000-0000-4000-8000-000000000001',other='71000000-0000-4000-8000-000000000002';
const scores={pace:60,shooting:70,passing:80,dribbling:75,defending:55,physical:65};
const row={...scores,member_id:id,revision:1,updated_at:'2026-10-07T00:00:00Z'};
const profile={id,auth_user_id:'actor',status:'active',role:'manager',officer_title:'treasurer',is_system_admin:false,must_change_password:false};
function deferred(){let resolve;const promise=new Promise(done=>{resolve=done});return{promise,resolve};}
function fixture(){const state={scope:'actor:1',caller:true,grant:true,freshCurrent:true,data:[row],error:null,verifyGate:null,rpcGate:null,throwRpc:false};const calls=[];const access=client.createMemberOverallAccess({scope:state.scope,version:0,getScope:()=>state.scope,verifyAccess:async()=>{calls.push('verify');if(state.verifyGate)await state.verifyGate.promise;return Object.assign(new Set(state.grant?['ratings.manage']:[]),{profiles:[],isCurrent:()=>state.freshCurrent});},rpc:async(name,args)=>{calls.push([name,args]);if(state.rpcGate)await state.rpcGate.promise;if(state.throwRpc)throw new Error('synthetic transport failure');return{data:state.data,error:state.error};},onChanged:()=>calls.push('changed')});return{state,calls,access,current:()=>state.caller};}
test('ability scope accepts eligible officers/system administrators and excludes ordinary/unlinked/restricted actors',()=>{const permission=new Set(['ratings.manage']);assert.ok(client.getMemberOverallScope('actor',profile,permission,1,true));assert.ok(client.getMemberOverallScope('actor',{...profile,is_test_account:true},permission,1,true));assert.ok(client.getMemberOverallScope('actor',{...profile,role:'member',officer_title:null,is_system_admin:true},permission,1,true));for(const patch of [{status:'inactive'},{must_change_password:true},{role:'member'},{officer_title:null},{auth_user_id:'someone'}])assert.equal(client.getMemberOverallScope('actor',{...profile,...patch},permission,1,true),'');assert.equal(client.getMemberOverallScope('actor',profile,new Set(),1,true),'');assert.equal(client.getMemberOverallScope('actor',profile,permission,1,false),'');});
test('read verifies current authority and queries only deduplicated selected targets',async()=>{const f=fixture();assert.deepEqual(await f.access.read([id,id],f.current),[row]);assert.deepEqual(f.calls,['verify',['get_member_overalls',{p_member_ids:[id]}]]);});
test('denied authority never dispatches a private RPC',async()=>{for(const patch of [{grant:false},{freshCurrent:false},{scope:'actor:2'},{caller:false}]){const f=fixture();Object.assign(f.state,patch);await assert.rejects(f.access.read([id],f.current),e=>e.kind==='forbidden');assert.equal(f.calls.some(Array.isArray),false);}});
test('actor or menu invalidation during authority/read/write awaits cannot expose results or announce a save',async()=>{for(const phase of ['verifyGate','rpcGate'])for(const action of ['read','save']){const f=fixture(),gate=deferred();f.state[phase]=gate;const pending=action==='read'?f.access.read([id],f.current):f.access.save(id,scores,0,f.current);await Promise.resolve();await Promise.resolve();f.state.scope='actor:3';gate.resolve();await assert.rejects(pending,e=>e.kind==='forbidden');assert.equal(f.calls.includes('changed'),false);}});
test('save uses expected revision and refreshes shared references only after a complete matching result',async()=>{const f=fixture();assert.deepEqual(await f.access.save(id,scores,0,f.current),row);assert.deepEqual(f.calls,['verify',['set_member_overall',{p_member_id:id,p_scores:scores,p_expected_revision:0}],'changed']);});
test('save revision conflicts and uncertain transports remain distinguishable without diagnostics',async()=>{for(const [error,kind] of [[{code:'40001',message:'private diagnostic'},'conflict'],[{code:'XX000',message:'private diagnostic'},'unknown']]){const f=fixture();f.state.error=error;await assert.rejects(f.access.save(id,scores,0,f.current),e=>e.kind===kind&&!e.message.includes('diagnostic'));assert.equal(f.calls.includes('changed'),false);}const f=fixture();f.state.throwRpc=true;await assert.rejects(f.access.save(id,scores,0,f.current),e=>e.kind==='unknown');});
test('permission errors refresh authority and do not announce success',async()=>{const f=fixture();f.state.error={code:'42501'};await assert.rejects(f.access.save(id,scores,0,f.current),e=>e.kind==='forbidden');assert.equal(f.calls.filter(c=>c==='verify').length,2);assert.equal(f.calls.includes('changed'),false);});
test('polluted read/save rows and malformed revision cannot be treated as confirmed data',async()=>{for(const data of [[{...row,member_id:other}],[row,row],[{...row,pace:0}],null]){const f=fixture();f.state.data=data;await assert.rejects(f.access.read([id],f.current),domain.MemberOverallError);}for(const data of [[],[{...row,revision:5}],[{...row,member_id:other}],null]){const f=fixture();f.state.data=data;await assert.rejects(f.access.save(id,scores,0,f.current),domain.MemberOverallError);assert.equal(f.calls.includes('changed'),false);}});
test('invalid scores/targets/revisions do not invoke verification or RPC',async()=>{for(const [member,values,revision] of [['bad',scores,0],[id,{...scores,pace:0},0],[id,scores,-1],[id,scores,1.5]]){const f=fixture();await assert.rejects(f.access.save(member,values,revision,f.current),e=>e.kind==='invalid');assert.deepEqual(f.calls,[]);}const f=fixture();assert.deepEqual(await f.access.read([],f.current),[]);await assert.rejects(f.access.read(['bad'],f.current),e=>e.kind==='invalid');});
test('production accepted-authority code increments ability generation for off-on and actor changes before React effects',()=>{const source=readFileSync(new URL('../components/clubhouse.tsx',import.meta.url),'utf8'),tree=ts.createSourceFile('clubhouse.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let key,assignment;function visit(node){if(ts.isVariableDeclaration(node)&&node.name.getText(tree)==='overallActorKey')key=node.initializer.getText(tree);if(ts.isExpressionStatement(node)&&node.getText(tree).startsWith('accessRef.current = { ...snapshot, owner, permissions: nextPermissions, ready: true, overallReady: true'))assignment=node.getText(tree);ts.forEachChild(node,visit);}visit(tree);assert.ok(key&&assignment);const accept=new Function('owner','snapshot','nextPermissions','accessRef',`const overallActorKey=${key};${assignment};return accessRef.current;`);const ref={current:{profile,permissions:new Set()}};const next=(permissions,p=profile)=>{ref.current=accept('actor',{...ref.current,profile:p},permissions,ref);return ref.current.overallGeneration;};const first=next(new Set(['ratings.manage']));const off=next(new Set());const restored=next(new Set(['ratings.manage']));assert.ok(off>first&&restored>off);assert.equal(next(new Set(['ratings.manage'])),restored);assert.ok(next(new Set(['ratings.manage']),{...profile,auth_user_id:'other'})>restored);});