import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import ts from 'typescript';
function load(file, imports = {}) { const source=readFileSync(new URL(file,import.meta.url),'utf8');const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};new Function('exports','require',code)(exports,(name)=>imports[name]);return exports; }
const domain=load('./member-overall.ts');
const client=load('./member-overall-client.ts',{'./member-overall':domain});
const id='71000000-0000-4000-8000-000000000001',other='71000000-0000-4000-8000-000000000002';
const scores={pace:60,shooting:70,passing:80,dribbling:75,defending:55,physical:65};
const row={...scores,member_id:id,revision:1,updated_at:'2026-10-07T00:00:00Z',response_count:4,event_count:2};
const profile={id,auth_user_id:'actor',status:'active',role:'manager',officer_title:'treasurer',is_system_admin:false,must_change_password:false};
function deferred(){let resolve;const promise=new Promise(done=>{resolve=done});return{promise,resolve};}
function fixture(){const state={scope:'actor:1',caller:true,grant:true,freshCurrent:true,data:[row],error:null,verifyGate:null,rpcGate:null,throwRpc:false};const calls=[];const access=client.createMemberOverallAccess({scope:state.scope,version:0,getScope:()=>state.scope,verifyAccess:async()=>{calls.push('verify');if(state.verifyGate)await state.verifyGate.promise;return Object.assign(new Set(state.grant?['ratings.manage']:[]),{profiles:[],isCurrent:()=>state.freshCurrent});},rpc:async(name,args)=>{calls.push([name,args]);if(state.rpcGate)await state.rpcGate.promise;if(state.throwRpc)throw new Error('synthetic transport failure');return{data:state.data,error:state.error};},onChanged:()=>calls.push('changed')});return{state,calls,access,current:()=>state.caller};}
test('ability scope accepts eligible officers/system administrators and excludes ordinary/unlinked/restricted actors',()=>{const permission=new Set(['ratings.manage']);assert.ok(client.getMemberOverallScope('actor',profile,permission,1,true));assert.ok(client.getMemberOverallScope('actor',{...profile,is_test_account:true},permission,1,true));assert.ok(client.getMemberOverallScope('actor',{...profile,role:'member',officer_title:null,is_system_admin:true},permission,1,true));for(const patch of [{status:'inactive'},{must_change_password:true},{role:'member'},{officer_title:null},{auth_user_id:'someone'}])assert.equal(client.getMemberOverallScope('actor',{...profile,...patch},permission,1,true),'');assert.equal(client.getMemberOverallScope('actor',profile,new Set(),1,true),'');assert.equal(client.getMemberOverallScope('actor',profile,permission,1,false),'');});
test('read verifies current authority and queries only deduplicated selected targets',async()=>{const f=fixture();assert.deepEqual(await f.access.read([id,id],f.current),[row]);assert.deepEqual(f.calls,['verify',['get_mixed_zone_overalls',{p_member_ids:[id]}]]);});
test('denied authority never dispatches a private RPC',async()=>{for(const patch of [{grant:false},{freshCurrent:false},{scope:'actor:2'},{caller:false}]){const f=fixture();Object.assign(f.state,patch);await assert.rejects(f.access.read([id],f.current),e=>e.kind==='forbidden');assert.equal(f.calls.some(Array.isArray),false);}});
test('production accepted-authority code increments ability generation for off-on and actor changes before React effects',()=>{const source=readFileSync(new URL('../components/clubhouse.tsx',import.meta.url),'utf8'),tree=ts.createSourceFile('clubhouse.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let key,mixedKey,assignment;function visit(node){if(ts.isVariableDeclaration(node)&&node.name.getText(tree)==='overallActorKey')key=node.initializer.getText(tree);if(ts.isVariableDeclaration(node)&&node.name.getText(tree)==='mixedZoneActorKey')mixedKey=node.initializer.getText(tree);if(ts.isExpressionStatement(node)&&node.getText(tree).startsWith('accessRef.current = { ...snapshot, owner, permissions: nextPermissions, ready: true, overallReady: true'))assignment=node.getText(tree);ts.forEachChild(node,visit);}visit(tree);assert.ok(key&&mixedKey&&assignment);const accept=new Function('owner','snapshot','nextPermissions','accessRef',`const overallActorKey=${key};const mixedZoneActorKey=${mixedKey};${assignment};return accessRef.current;`);const ref={current:{profile,permissions:new Set()}};const next=(permissions,p=profile)=>{ref.current=accept('actor',{...ref.current,profile:p},permissions,ref);return ref.current.overallGeneration;};const first=next(new Set(['ratings.manage']));const off=next(new Set());const restored=next(new Set(['ratings.manage']));assert.ok(off>first&&restored>off);assert.equal(next(new Set(['ratings.manage'])),restored);assert.ok(next(new Set(['ratings.manage']),{...profile,auth_user_id:'other'})>restored);const grants=new Set(['ratings.manage']);next(grants);const before=ref.current.mixedZoneGeneration;for(const patch of [{status:'inactive'},{must_change_password:true},{is_test_account:true},{auth_user_id:'other'}]){const previous=ref.current.mixedZoneGeneration;next(grants,{...profile,...patch});assert.ok(ref.current.mixedZoneGeneration>previous);const changed=ref.current.mixedZoneGeneration;next(grants);assert.ok(ref.current.mixedZoneGeneration>changed);}assert.ok(ref.current.mixedZoneGeneration>before);const stable=ref.current.mixedZoneGeneration;next(new Set());next(grants);assert.equal(ref.current.mixedZoneGeneration,stable); });

test('manual overall save is disabled without any RPC even for privileged actors',async()=>{const f=fixture();await assert.rejects(f.access.save(id,scores,0,f.current),e=>e.kind==='forbidden');assert.deepEqual(f.calls,[])});
test('aggregate replies cannot cross actor or selection invalidation during verify and read awaits',async()=>{for(const phase of ['verifyGate','rpcGate']){const f=fixture(),gate=deferred();f.state[phase]=gate;const pending=f.access.read([id],f.current);await Promise.resolve();await Promise.resolve();f.state.scope='actor:3';gate.resolve();await assert.rejects(pending,e=>e.kind==='forbidden');assert.equal(f.calls.includes('changed'),false)}});
test('aggregate reads reject foreign, duplicate, malformed and missing sample rows',async()=>{for(const data of [[{...row,member_id:other}],[row,row],[{...row,pace:-1}],[{...row,response_count:undefined}],[{...row,event_count:0}],null]){const f=fixture();f.state.data=data;await assert.rejects(f.access.read([id],f.current),domain.MemberOverallError)}});
test('aggregate denied RPC refreshes authority and invalid targets never dispatch',async()=>{const f=fixture();f.state.error={code:'42501'};await assert.rejects(f.access.read([id],f.current),e=>e.kind==='forbidden');assert.equal(f.calls.filter(c=>c==='verify').length,2);const invalid=fixture();await assert.rejects(invalid.access.read(['bad'],invalid.current),e=>e.kind==='invalid');assert.deepEqual(invalid.calls,[]);assert.deepEqual(await invalid.access.read([],invalid.current),[])});
