import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import ts from 'typescript';
function load(file,imports={}){const code=ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};new Function('exports','require',code)(exports,name=>imports[name]);return exports;}
const overall=load('./member-overall.ts'),attendance=load('./attendance.ts'),domain=load('./mixed-zone.ts',{'./member-overall':overall,'./attendance':attendance}),client=load('./mixed-zone-client.ts',{'./member-overall':overall,'./mixed-zone':domain});
const eventId='71000000-0000-4000-8000-000000000001',memberId='71000000-0000-4000-8000-000000000002';
const scores={pace:4,shooting:4,passing:4,dribbling:4,defending:4,physical:4},row={...scores,event_id:eventId,member_id:memberId,revision:1,updated_at:'2026-10-07T00:00:00Z'};
function deferred(){let resolve;const promise=new Promise(done=>{resolve=done});return{promise,resolve};}
function fixture(){const state={scope:'owner:1',caller:true,verified:true,data:[row],error:null,verifyGate:null,rpcGate:null,throwRpc:false},calls=[];const access=client.createMixedZoneAccess({scope:state.scope,version:0,getScope:()=>state.scope,verifyAccess:async()=>{calls.push('verify');if(state.verifyGate)await state.verifyGate.promise;return state.verified},refreshWindow:async()=>{calls.push('refresh')},rpc:async(name,args)=>{calls.push([name,args]);if(state.rpcGate)await state.rpcGate.promise;if(state.throwRpc)throw Error('synthetic transport');return{data:state.data,error:state.error}},onChanged:()=>calls.push('changed')});return{state,calls,access,current:()=>state.caller};}
test('mixed zone actor scope accepts ordinary linked active actors and excludes restricted identities',()=>{const profile={id:memberId,auth_user_id:'owner',status:'active',role:'member',officer_title:null,must_change_password:false,is_test_account:false};assert.ok(client.getMixedZoneScope('owner',profile,1,true));for(const patch of [{auth_user_id:'other'},{status:'inactive'},{must_change_password:true},{is_test_account:true}])assert.equal(client.getMixedZoneScope('owner',{...profile,...patch},1,true),'');assert.equal(client.getMixedZoneScope('owner',profile,1,false),'');assert.notEqual(client.getMixedZoneScope('owner',profile,1,true),client.getMixedZoneScope('owner',profile,2,true));});
test('mixed zone read is one event batch and never sends an actor id',async()=>{const f=fixture();assert.deepEqual(await f.access.read(eventId,f.current),[row]);assert.deepEqual(f.calls,['verify',['get_mixed_zone_entries',{p_event_id:eventId}]]);});
test('mixed zone write uses CAS without actor payload and announces only a matching confirmed result',async()=>{const f=fixture();assert.deepEqual(await f.access.save(eventId,memberId,scores,0,f.current),row);assert.deepEqual(f.calls,['verify',['set_mixed_zone_entry',{p_event_id:eventId,p_member_id:memberId,p_scores:scores,p_expected_revision:0}],'changed']);});
test('revoked authority never dispatches and actor/target scopes cannot cross verify or RPC awaits',async()=>{for(const patch of [{verified:false},{caller:false},{scope:'owner:2'}]){const f=fixture();Object.assign(f.state,patch);await assert.rejects(f.access.read(eventId,f.current),e=>e.kind==='forbidden');assert.equal(f.calls.some(Array.isArray),false)}for(const phase of ['verifyGate','rpcGate'])for(const action of ['read','save'])for(const invalidation of ['scope','caller']){const f=fixture(),gate=deferred();f.state[phase]=gate;const promise=action==='read'?f.access.read(eventId,f.current):f.access.save(eventId,memberId,scores,0,f.current);await Promise.resolve();await Promise.resolve();if(invalidation==='scope')f.state.scope='owner:3';else f.state.caller=false;gate.resolve();await assert.rejects(promise,e=>e.kind==='forbidden');assert.equal(f.calls.includes('changed'),false)}});
test('error codes preserve forbidden invalid conflict and unknown recovery without exposing server diagnostics',async()=>{for(const [code,kind] of [['42501','forbidden'],['40001','conflict'],['22023','invalid'],['XX000','unknown']]){const f=fixture();f.state.error={code,message:'private diagnostic'};await assert.rejects(f.access.save(eventId,memberId,scores,0,f.current),e=>e.kind===kind&&!e.message.includes('diagnostic'));assert.equal(f.calls.includes('changed'),false);if(code==='42501')assert.equal(f.calls.filter(c=>c==='verify').length,2)}const f=fixture();f.state.throwRpc=true;await assert.rejects(f.access.save(eventId,memberId,scores,0,f.current),e=>e.kind==='unknown');});
test('malformed read/save and partial responses cannot become confirmed data',async()=>{for(const data of [null,[row,row],[{...row,event_id:memberId}],[{...row,physical:6}],[{...row,revision:0}]]){const f=fixture();f.state.data=data;await assert.rejects(f.access.read(eventId,f.current),domain.MixedZoneError)}for(const data of [[],[row,row],[{...row,member_id:eventId}],[{...row,revision:6}],[{...row,pace:3}],null]){const f=fixture();f.state.data=data;await assert.rejects(f.access.save(eventId,memberId,scores,0,f.current),domain.MixedZoneError);assert.equal(f.calls.includes('changed'),false)}});
test('invalid or incomplete drafts never dispatch a request',async()=>{for(const [event,member,values,revision] of [['bad',memberId,scores,0],[eventId,'bad',scores,0],[eventId,memberId,{...scores,pace:null},0],[eventId,memberId,{...scores,pace:0},0],[eventId,memberId,scores,-1],[eventId,memberId,scores,1.5]]){const f=fixture();await assert.rejects(f.access.save(event,member,values,revision,f.current),e=>e.kind==='invalid');assert.deepEqual(f.calls,[])}});

test('authoritative permission denial remains forbidden even if the followup authority refresh loses transport',async()=>{
  let verifies=0;const access=client.createMixedZoneAccess({scope:'owner:1',version:0,getScope:()=> 'owner:1',verifyAccess:async()=>{if(++verifies===2)throw Error('synthetic refresh failure');return true},refreshWindow:async()=>{},rpc:async()=>({data:null,error:{code:'42501'}}),onChanged:()=>{throw Error('must not announce')}});
  await assert.rejects(access.save(eventId,memberId,scores,0,()=>true),e=>e.kind==='forbidden');assert.equal(verifies,2);
});
